import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { BRIEFS } from './src/briefs.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Each brief is its own static HTML entry (generated by scripts/gen-briefs.mjs)
// so social scrapers get per-brief meta. The full page stays at index.html.
const briefInputs = Object.fromEntries(
  BRIEFS.map((b) => [`brief-${b.slug}`, resolve(__dirname, 'b', b.slug, 'index.html')])
);

// On Vercel we serve from the domain root; on GitHub Pages / preview we serve
// from a project subpath that matches the repo name.
export default defineConfig({
  plugins: [react()],
  base: process.env.VERCEL ? '/' : '/aiffected/',
  build: {
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        ...briefInputs,
      },
    },
  },
});
