// ---------------------------------------------------------------------------
// Briefs: single-concept, share-sized mini-pages in the same style as the full
// site. Each is its own static URL (/b/<slug>/) with its own social-card meta,
// and each funnels to the matching section of the full page.
//
// Adding a brief = adding one entry here, then running `npm run briefs` to
// regenerate the static HTML (and `npm run og` to refresh the share images).
// ---------------------------------------------------------------------------

export const BRIEFS = [
  {
    slug: 'gdp-up-jobs-down',
    eyebrow: 'The paradox',
    title: ['The economy can grow ', { em: '+20%', tone: 'up' }, ' while ', { em: '1 in 5', tone: 'down' }, ' lose their jobs.'],
    dek: 'GDP measures what we make — not how many of us it takes to make it. Generative AI is pulling those two apart. Drag the slider.',
    kind: 'paradox',
    voice: 'amodei',
    deep: 'simulator',
    cta: 'See how it works →',
    ogTitle: 'GDP up, jobs down — the paradox',
    ogDesc: 'How an economy can grow 10–20% while unemployment climbs from 4% toward 20%. A 30-second interactive brief.',
  },
  {
    slug: 'the-human-ledger',
    eyebrow: 'The human ledger',
    title: ['A paycheck was never the ', { em: 'only thing', tone: 'accent' }, ' a job paid out.'],
    dek: 'Hand everyone an income and you refund one line of this ledger. The other four, money can’t buy.',
    kind: 'ledger',
    voice: 'sinek',
    deep: 'society',
    cta: 'Draw your own social contract →',
    ogTitle: 'The human ledger — what a job really pays out',
    ogDesc: 'A wage, yes — but also structure, contribution, status, belonging. A money-only answer leaves four lines unpaid.',
  },
  {
    slug: 'now-what',
    eyebrow: 'The question underneath',
    title: ['If we don’t need everyone to work, ', { em: 'who is it for?', tone: 'accent' }],
    dek: 'A job was three quiet promises: I make something better · I provide for the people I love · I pay into the world that raised me. Pull the job and they come loose — from yourself out to the world.',
    kind: 'rings',
    voice: 'keynes',
    deep: 'meaning',
    cta: 'Sit with the whole question →',
    ogTitle: 'Now what? — purpose after work',
    ogDesc: 'If machines make the wealth and we share it out, would any of it mean anything? The question the economics can’t answer.',
  },
  {
    slug: 'the-great-decoupling',
    eyebrow: 'The mechanism',
    title: ['For 200 years pay rose with ', { em: 'productivity', tone: 'up' }, '. Then it ', { em: 'stopped', tone: 'down' }, '.'],
    dek: 'The economy keeps making more per hour. Your paycheck stopped coming along for the ride. Economists call it the great decoupling — and AI pours fuel on it.',
    kind: 'decoupling',
    voice: 'brynjolfsson',
    deep: 'mechanism',
    cta: 'See the mechanism →',
    ogTitle: 'The great decoupling — when pay stopped following productivity',
    ogDesc: 'For two centuries wages rose with output per hour. Then they split. AI widens the gap.',
  },
  {
    slug: 'escape-route-closes',
    eyebrow: 'Wave 2 · robotics',
    title: ['The “safe” jobs were only safe ', { em: 'until the robots arrived', tone: 'down' }, '.'],
    dek: 'Wave 1 hit the desks. Wave 2 is robotics — and the manual work people fled into for safety floods next. Flip the wave and watch.',
    kind: 'sectors',
    voice: 'frey',
    deep: 'waves',
    cta: 'Explore the three waves →',
    ogTitle: 'The escape route closes — robotics floods the safe jobs',
    ogDesc: 'The manual jobs people fled into for safety — warehouses, driving, repair, care — are next.',
  },
  {
    slug: 'who-gets-the-gains',
    eyebrow: 'The distribution',
    title: ['When machines make the money, ', { em: 'who gets it?', tone: 'accent' }],
    dek: 'Once output detaches from labour, the gains flow to whoever owns the machines — unless we decide otherwise. Move the dial.',
    kind: 'split',
    voice: 'piketty',
    deep: 'simulator',
    cta: 'Build the whole economy →',
    ogTitle: 'Who gets the gains when machines make the money?',
    ogDesc: 'Output detaches from labour and income flows to whoever owns the machines — unless policy intervenes.',
  },
  {
    slug: 'still-in-the-loop',
    eyebrow: 'Wave 3 · autonomy',
    title: ['What happens when the machines ', { em: 'no longer need us', tone: 'down' }, '?'],
    dek: 'Wave 3 is autonomy: systems that set their own goals and improve themselves. The question stops being about jobs and becomes whether humans keep any leverage at all.',
    kind: 'gauge',
    voice: 'harari',
    deep: 'waves',
    cta: 'Reach Wave 3 →',
    ogTitle: 'Still in the loop? — the autonomy question',
    ogDesc: 'When AI runs the whole loop itself, the question stops being jobs and becomes human leverage.',
  },
  {
    slug: 'is-it-alarmist',
    eyebrow: 'The strongest objection',
    title: ['Is this just ', { em: 'alarmism?', tone: 'accent' }],
    dek: 'Every revolution destroyed jobs and created new ones we couldn’t imagine. Won’t AI do the same? It’s the best argument against all of this — so take it seriously.',
    kind: 'debate',
    voice: 'autor',
    deep: 'alarmist',
    cta: 'Weigh both sides →',
    ogTitle: 'Is this just alarmism? — the strongest objection',
    ogDesc: 'Every revolution created new jobs we couldn’t imagine. Will AI? The best argument against the doom case.',
  },
];

export const briefBySlug = (slug) => BRIEFS.find((b) => b.slug === slug);
